### ISSUE TITLE
We site changes

### ISSUE THREAD

**Issue by DavinciDreams** [TheNexusCity/-web#1]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/26981091?key=7c7f86fd6ae914bf37500baf8bb31dba&size=orig) 

---
**Source URL**:
[https://cdn.discordapp.com/attachments/957486751318966342/973821096459632682/Mockup-design02.jpg](https://cdn.discordapp.com/attachments/957486751318966342/973821096459632682/Mockup-design02.jpg)

**Comment by Mandeep-Kaur27** [comment]
![Mockup-design03](https://user-images.githubusercontent.com/102357640/168331636-d05fe8d4-13ba-4a2a-8627-9dd6d7835952.jpg)
